version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.15
    working_directory: /go/src/github.com/akpan-daniel/play_with_circleci
    steps:
      - checkout
      - run: go test -v ./...
